# Data Mining Lab 3 Pipeline Assignment

**Medium articles** are used to disseminate knowledge and are written on a wide range of technical and non-technical topics. Users subscribe to different reading lists where reading lists represent either domains or certain topics. This naturally gives rise to a network structure where articles may belong to the same reading lists and hence are related to each other. Each article belongs to a certain topic. Automatically assigning articles to topics is very valuable for search applications. **The goal of this task is to classify articles by predicting their topics.**

A dataset of medium articles along with subscription lists and topic tags is provided. The task is to classify articles into tags (i.e., topics), leveraging the network structure arising from relations using the subscription lists. Specifically, two nodes are connected if they share at least one list.

**For this task you may only use the following libraries**: `numpy`, `pandas`, `matplotlib`, `networkx`, `gensim`.


In [23]:
from collections import defaultdict
from itertools import combinations
from pathlib import Path

import networkx as nx
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from gensim.models import Word2Vec

## Data loading

The data is provided in three files which can be found in the `data` directory:

- `articles.csv`: Contains the articles along with the subscription lists and some metadata.
- `test_data.csv`: Contains a subset of nodes (articles) along with their labels (topics) used for testing.
- `train_data.csv`: Contains the remaining nodes (articles) along with their labels (topics).

**Important**: There is no specific training data requried for this assignment, since the node embeddings (task 3) are trained on the entire graph. The nodes in `train_data.csv` must be used for the kNN classifier, i.e., the computed nearest neighbors for a test node may only be nodes from this file.

Let's use `pandas` to read these files:


In [24]:
articles = pd.read_csv(Path("data") / "articles.csv")
articles["node_id"] = articles.index
articles["lists"] = articles["lists"].str.split("; ")
test_data = pd.read_csv(Path("data") / "test_data.csv")
train_data = pd.read_csv(Path("data") / "train_data.csv")

Note that we have assigned node IDs based on where each article is located in the file.

We can now inspect the individual data frames:


In [25]:
articles.head(2)

article  \
0  https://medium.com/@maniakacademy/code-demo-sh...   
1  https://medium.com/towards-artificial-intellig...   

                                               title  \
0  Code/Demo Share: Palo Alto Firewall Network In...   
1              Clustering using Social Graph Network   

                                            subtitle                 author  \
0  IP is broken as a unit of Control! IDENTITY as...       Sebastian Maniak   
1  A Social Graph Network can be formed when ther...  Naveed Ahmed Janvekar   

         date                                              lists  node_id  
0  2022-08-17  [https://medium.com/@zemmali1990/list/aws-49f6...        0  
1  2022-01-29  [https://medium.com/@TomaszCieplak/list/graph-...        1

In [26]:
test_data.head(2)

node_id                    label
0     2291  artificial-intelligence
1     7292  artificial-intelligence

Next, let's create our graph. We'll create one node for each article and insert an edge between two articles if they share at least one subscription list:


In [27]:
medium_graph = nx.Graph()
medium_graph.add_nodes_from(articles["node_id"].to_list())

list_to_nodes = defaultdict(set)
for _, row in articles[["node_id", "lists"]].iterrows():
    for l in row["lists"]:
        list_to_nodes[l].add(row["node_id"])

for node_ids in list_to_nodes.values():
    medium_graph.add_edges_from(combinations(node_ids, 2))

## Tasks

1. Familiarization: Analyze the graph. Compute and plot statistics such as the number of nodes, number of edges, number of neighbors of each node, and so on. Are there any isolated nodes (i.e., nodes that do not have a single neighbor)?
2. Compute spectral node embeddings.
3. Perform random walks on the graph to obtain a set of sequences of nodes. Use those sequences to compute node embeddings. Hint: You may use the Word2vec implementation of the gensim library for this task. By treating each node as a word, this method will give you node embeddings.
4. Implement a simple k-nearest neighbor classifier: For each node (medium article) in the test set, compute its nearest neighbors (based on the similarity of node embeddings). The classifier assigns a label (i.e., a topic) based on the topics of the nearest neighbors. Specifically, the predicted topic is simply the most common topic among the nearest neighbors. Compare both sets of node embeddings in terms of performance. Which one works better?


In [28]:
# Q1
num_nodes = medium_graph.number_of_nodes()
print("Number of nodes:", num_nodes)
num_edges = medium_graph.number_of_edges()
print("Number of edges:", num_edges)

# Then we also print the degrees of several nodes
print_lim = 5
isolated = 0
for n in medium_graph.nodes:
    deg = medium_graph.degree(n)
    if print_lim > 0:
        print(f"Node {n} has {deg} neighbors")
        print_lim -= 1
    if deg == 0:
        isolated += 1
print(f"There are {isolated} isolated nodes")

Number of nodes: 27718
Number of edges: 2014162
Node 0 has 144 neighbors
Node 1 has 102 neighbors
Node 2 has 18 neighbors
Node 3 has 34 neighbors
Node 4 has 15 neighbors
There are 347 isolated nodes


In [29]:
# Q2
def compute_spectral_embeddings(graph: nx.Graph, dim: int) -> np.ndarray:
    """Perform spectral clustering on the graph and compute low-dimensional node representations.
    Does not normalize the Laplacian.

    Args:
        graph (nx.Graph): The graph.
        dim (int): The dimension of representations. This corresponds to the number of eigenvectors used.

    Returns:
        np.ndarray: Node representations (sorted by node ID, ascending), shape (num_nodes, dim).
    """
    adjacency_matrix = nx.to_numpy_array(graph, nodelist=sorted(graph.nodes))

    # make sure the matrix is symmetric
    assert (adjacency_matrix == adjacency_matrix.T).all()

    n = adjacency_matrix.shape[0]
    L = np.zeros((n,n))
    for i in range(n):
        L[i][i] = np.sum(adjacency_matrix[i])
    L -= adjacency_matrix
    _, evecs = np.linalg.eigh(L)
    return evecs[:, :dim]

In [38]:
# Q3
def random_walks(graph: nx.Graph, num_walks: int, walk_length: int) -> np.ndarray:
    """Perform random walks on an unweighted graph.

    Args:
        graph (nx.Graph): The graph.
        num_walks (int): The number of random walks for each node.
        walk_length (int): The number of nodes in a random walk.

    Returns:
        np.ndarray: The random walks, shape (n_nodes * num_walks, walk_length)
    """
    result = np.zeros((graph.number_of_nodes() * num_walks, walk_length))

    for idx, node in enumerate(graph.nodes):
        for walk in range(num_walks):
            i = idx * num_walks + walk
            for j in range(walk_length):
                result[i, j] = node
                node = np.random.choice(graph[node])

    return result

We are making a copy of the graph, without the isolated nodes, because the random walks function can't deal with those.

In [36]:
clean_graph = medium_graph.copy()
clean_graph.remove_nodes_from([n for n, d in medium_graph.degree() if d == 0])

In [39]:
print(random_walks(clean_graph, num_walks=5, walk_length=10))

[[14110. 12088. 15303. ... 24994.  6450. 17537.]
 [13508. 24762.  3849. ... 12088.   260. 10977.]
 [17751. 26075. 22490. ... 20404.  6010. 16089.]
 ...
 [10861. 23780. 23035. ...  9808.  9808.  8872.]
 [24823.  8872. 23780. ... 21386. 23035. 21386.]
 [23780. 21386. 23780. ... 21386. 23780.  9808.]]
